apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-loadbalancer
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-mqtt-transport
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 8883
      targetPort: 8883
      name: mqtts
    # Optional: mapping of 443 port to 8883 to ease firewall traversal
    - port: 443
      targetPort: 8883
      name: mqtts-443
