{{- if .Values.cassandra.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cassandra.initDBConfigMap }}
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
  data:
    "01-init.cql": |
       CREATE KEYSPACE IF NOT EXISTS {{ .Values.cassandraInitDB.keyspace }}
         WITH replication = {
           'class' : '{{ .Values.cassandraInitDB.replication.class }}',
           'replication_factor' : {{ .Values.cassandraInitDB.replication.factor }}
         };
{{- end }}
