apiVersion: apps/v1
kind: {{ .Values.coap.kind }}
metadata:
  name: {{ .Release.Name }}-coap-transport
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
spec:
{{- if not .Values.coap.autoscaling.enabled }}
  replicas: {{ .Values.coap.replicaCount }}
{{- end }}
{{- if eq .Values.coap.kind "StatefulSet" }}
  podManagementPolicy: "Parallel"
  serviceName: tb-coap-transport
{{- end }}
  selector:
    matchLabels:
      {{- include "thingsboard.selectorLabels-coap" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.coap.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "thingsboard.selectorLabels-coap" . | nindent 8 }}
    spec:
      {{- with .Values.coap.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thingsboard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.coap.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.coap.securityContext | nindent 12 }}
          image: "{{ .Values.coap.image.server | default .Values.global.image.server }}/{{ .Values.coap.image.repository }}:{{ .Values.coap.image.tag | default .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.coap.image.pullPolicy | default .Values.global.image.pullPolicy}}
          ports:
          - containerPort: {{ .Values.coap.port.number }}
            name: {{ .Values.coap.port.name }}
            protocol: {{ .Values.coap.port.protocol }}
          env:
          - name: TB_SERVICE_ID
            value: "tb-coap-transport"
          - name: TB_QUEUE_TYPE
            value: "kafka"
          - name: COAP_BIND_ADDRESS
            value: "0.0.0.0"
          - name: COAP_BIND_PORT
            value: "{{ .Values.coap.port.number }}"
          - name: COAP_TIMEOUT
            value: "{{ .Values.coap.timeout }}"
          - name: TB_KAFKA_SERVERS
            value: "{{ .Release.Name }}-kafka-headless:9092"
          volumeMounts:
            - mountPath: /config
              name: {{ .Release.Name }}-coap-transport-config
          resources:
            {{- toYaml .Values.coap.resources | nindent 12 }}
      volumes:
        - name: {{ .Release.Name }}-coap-transport-config
          configMap:
            name: {{ .Release.Name }}-coap-transport-config
            items:
            - key: conf
              path:  tb-coap-transport.conf
            - key: logback
              path:  logback.xml
        - name: {{ .Release.Name }}-node-logs
          emptyDir: {}
      {{- with .Values.coap.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.coap.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.coap.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
