{{- if .Values.ingress.enabled -}}
{{- $fullName := include "thingsboard.fullname" . -}}
{{- $releaseName := .Release.Name -}}
{{- $ingressHost := .Values.ingress.host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ $ingressHost }}
    secretName: {{ $releaseName }}-tls
  {{- end }}
  rules:
    - host: {{ $ingressHost }}
      http:
         paths:
          - path: /api/v1/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-http
                port:
                  number: {{ .Values.http.service.port }}
          - path: /api/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-node
                port:
                  number: {{ .Values.node.service.port }}
          - path: /swagger.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-node
                port:
                  number: {{ .Values.node.service.port }}
          - path: /webjars.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-node
                port:
                  number: {{ .Values.node.service.port }}
          - path: /v2/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-node
                port:
                  number: {{ .Values.node.service.port }}
          - path: /v3/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-node
                port:
                  number: {{ .Values.node.service.port }}
          - path: /static/rulenode/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-node
                port:
                  number: {{ .Values.node.service.port }}
          - path: /assets/help/.*/rulenode/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-node
                port:
                  number: {{ .Values.node.service.port }}
          - path: /oauth2/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-node
                port:
                  number: {{ .Values.node.service.port }}
          - path: /login/oauth2/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-node
                port:
                  number: {{ .Values.node.service.port }}
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-webui
                port:
                  number: {{ .Values.webui.service.port }}
          - path: /.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-webui
                port:
                  number: {{ .Values.webui.service.port }}
{{- end }}
