apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ .Release.Name }}-init-tb-db'
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      imagePullSecrets:
        - name: '{{ .Release.Name }}-container-registry'
      initContainers:
        - name: check-db-ready
          image: postgres:{{ index .Values "postgresql-ha" "postgresqlImage" "tag" }}
          command: ['sh', '-c',
            'until pg_isready -h {{ .Release.Name }}-postgresql-ha-pgpool -p 5432;
            do echo waiting for database; sleep 2; done;']
      containers:
      - name: init-db
        envFrom:
        - configMapRef:
            name: '{{ .Release.Name }}-node-db-config'
        volumeMounts:
          - mountPath: /config
            name: '{{ .Release.Name }}-node-config'
        image: "{{ .Values.node.image.server | default .Values.global.image.server }}/{{ .Values.node.image.repository }}:{{ .Values.node.image.tag | default .Values.global.image.tag }}"
        command:
          - "/bin/bash"
        args:
          - "-c"
          - "start-tb-node.sh"
        env:
        - name: INSTALL_TB
          value: "true"
        - name: LOAD_DEMO
          value: "{{ .Values.node.loadDemo }}"
      restartPolicy: Never
      volumes:
        - name: '{{ .Release.Name }}-node-config'
          configMap:
            name: '{{ .Release.Name }}-node-config'
            items:
            - key: conf
              path: thingsboard.conf
            - key: logback
              path: logback.xml
