apiVersion: v1
kind: Service
metadata:
  name: {{ include "thingsboard.fullname" . }}-node
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.node.service.type }}
  ports:
    - port: {{ .Values.node.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "thingsboard.selectorLabelsNode" . | nindent 4 }}
