apiVersion: apps/v1
kind: {{ .Values.webui.kind }}
metadata:
  name: {{ .Release.Name }}-web-ui
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
spec:
{{- if not .Values.webui.autoscaling.enabled }}
  replicas: {{ .Values.webui.replicaCount }}
{{- end }}
{{- if eq .Values.webui.kind "StatefulSet" }}
  podManagementPolicy: "Parallel"
  serviceName: tb-mqtt-transport
{{- end }}
  selector:
    matchLabels:
      {{- include "thingsboard.selectorLabels-webui" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.webui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "thingsboard.selectorLabels-webui" . | nindent 8 }}
    spec:
      {{- with .Values.webui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thingsboard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.webui.securityContext | nindent 12 }}
          image: "{{ .Values.webui.image.server | default .Values.global.image.server }}/{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag | default .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.webui.image.pullPolicy | default .Values.global.image.pullPolicy}}
          ports:
          - containerPort: {{ .Values.webui.port.number }}
            name: {{ .Values.webui.port.name }}
          env:
          - name: HTTP_BIND_ADDRESS
            value: "0.0.0.0"
          - name: HTTP_BIND_PORT
            value: "{{ .Values.webui.port.number }}"
          - name: TB_ENABLE_PROXY
            value: "false"
          - name: LOGGER_LEVEL
            value: "info"
          - name: LOG_FOLDER
            value: "logs"
          - name: LOGGER_FILENAME
            value: "tb-web-ui-%DATE%.log"
          - name: DOCKER_MODE
            value: "true"
          livenessProbe:
            httpGet:
              path: /index.html
              port: {{ .Values.webui.port.name }}
            initialDelaySeconds: 120
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.webui.resources | nindent 12 }}
      {{- with .Values.webui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
